import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import path from 'path';
import { fileURLToPath } from 'url';
import multer from 'multer';
import { body, validationResult } from 'express-validator';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import spaceRoutes from './routes/spaceRoutes.js';
import testimonialRoutes from './routes/testimonialRoutes.js';
import { publicSpace, publicWall } from './controllers/spaceController.js';
import { createTestimonial } from './controllers/testimonialController.js';
const app = express(); const __dirname = path.dirname(fileURLToPath(import.meta.url));
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true })); app.use(express.json()); app.use(cookieParser()); app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
const upload = multer({ dest: path.join(__dirname, 'uploads'), limits: { fileSize: 3 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, ['image/jpeg','image/png','image/webp'].includes(file.mimetype)) });
const validate = (req, res, next) => { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(400).json({ errors: errors.array() }); next(); };
app.get('/api/health', (_, res) => res.json({ status: 'ok' })); app.use('/api/auth', authRoutes); app.use('/api/spaces', spaceRoutes); app.use('/api/testimonials', testimonialRoutes);
app.get('/api/public/spaces/:slug', publicSpace); app.get('/api/public/spaces/:slug/wall', publicWall); app.post('/api/public/spaces/:slug/testimonials', upload.single('avatar'), body('email').isEmail(), body('clientName').trim().notEmpty(), body('companyRole').trim().notEmpty(), body('reviewText').trim().isLength({ min: 10 }), body('rating').isInt({ min: 1, max: 5 }), validate, createTestimonial);
app.use((error, _, res, __) => res.status(500).json({ message: error.message }));
connectDB(); app.listen(process.env.PORT || 5000, () => console.log(`API running on port ${process.env.PORT || 5000}`));
